# Generated by Django 3.0.4 on 2020-05-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default='person1.jpg', upload_to='photos/'),
        ),
    ]
